version: "3.3"

services:
  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db: